package srs.util.enums;

public enum ActionEnum {
    MOVE,
    PIECE_TAKING,
    CASTLING_UL,
    CASTLING_BL,
    CASTLING_UR,
    CASTLING_BR,
    PAWN_PROMOTION_QUEEN,
    PAWN_PROMOTION_BISHOP,
    PAWN_PROMOTION_KNIGHT,
    PAWN_PROMOTION_ROOK,
}
